let data = [
    "{\"categories\": [\"BORETS\", \"SLB\", \"EDT\", \"DAQING\", \"JSC\", \"BAKER\", \"ALK\", \"GE\"], \"data\": {\"1\": [16, 15, 21, 18, 19, 18, 15, 13], \"2\": [46, 37, 40, 29, 45, 49, 40, 29], \"3\": [3, 7, 7, 9, 5, 6, 6, 7]}, \"title\": \"Trends in Failures\", \"x_label\": \"Vendor\", \"y_label\": \"Number of Failures\", \"text\": \"The length of the pipeline and the reason of failure are directly correlated. When pipelines are longer, the expectations that there is an operational failure or corrosion are high due to inconsistency in maintenance and inspection. That is evident in the chart with high rates of operational and mechanical failure of pipelines that are longer that 151 KM. On the other hand, medium length pipelines that are around 101-150 KM have equal chances of a failure happening due to any reason. Short pipelines are less prone to mechanical or operational failures. However, they are more likely to fail due to third party activity such as construction. <br />•\tThe length of the pipeline is directly related to reason of failure. The inconsistency in the category statistics shows this. <br />•\tAs pipelines lengthen, the reason of failure leans more towards the operations and mechanics of the pipeline itself.<br />•\tAs the pipeline shortens, the reason of failure is directed more towards natural or uncontrollable circumstances. <br />\"}\n",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
];