let word = [
    "{\"categories\":[\"BORETS\",\"SLB\",\"EDT\",\"DAQING\",\"JSC\",\"BAKER\",\"ALK\",\"GE\"],\"data\":{\"1\":[16,15,21,18,19,18,15,13],\"2\":[46,37,40,29,45,49,40,29],\"3\":[3,7,7,9,5,6,6,7]},\"title\":\"Trends in Failures\",\"x_label\":\"Vendor\",\"y_label\":\"Number of Failures\",\"text\":\"The length of the pipeline and the reason of failure are directly correlated. When pipelines are longer, the expectations that there is an operational failure or corrosion are high due to inconsistency in maintenance and inspection. That is evident in the chart with high rates of operational and mechanical failure of pipelines that are longer that 151 KM. On the other hand, medium length pipelines that are around 101-150 KM have equal chances of a failure happening due to any reason. Short pipelines are less prone to mechanical or operational failures. However, they are more likely to fail due to third party activity such as construction. <br/>- The length of the pipeline is directly related to reason of failure. The inconsistency in the category statistics shows this.<br/> - As pipelines lengthen, the reason of failure leans more towards the operations and mechanics of the pipeline itself.<br/>- As the pipeline shortens, the reason of failure is directed more towards natural or uncontrollable circumstances. <br/>\",\"text_height\":150}",
    "{\"categories\":[\"Gas\",\"Oil\",\"Water\"],\"data\":{\"1\":[73,62,0],\"2\":[159,148,8],\"3\":[25,20,5]},\"title\":\"Trends in Failures\",\"x_label\":\"Type\",\"y_label\":\"Number of Failures\",\"text\":\"When analyzing the life span of pipelines, the expectations are as follows: The first year the pipe is under performance test, hence the failure rate is at a fair level. The second year the failure rate is the highest due to the pipe being in production without maintenance or inspection. The third year is expected to have the least number of failures due to emergency maintenance and inspection done in year 2. Past the third year, the failure rate is expected to grow as the pipeline ages. The chart is a visual representation of the trend in early age of the pipeline against the type of fluid that the pipeline carries. For any pipe age and any pipeline type the statistics are consistent in showing that the rate of failure in pipelines of type gas are higher than those of type oil or water. With pipelines of oil with the second highest rate of failures, and pipelines of type water fail rarely. Experts expect the rate of water pipeline failures to be the highest. All pipeline types are more prone to failure two years into their first installation date as oppose to their lifespan being three or one year of age. This allows us to conclude that the number of years:<br />\\n•  Pipelines of types gas have the highest number of failures for any pipeline life span. <br />\\n•  Pipelines of type gas and oil which are one year of age have the second highest number of failures due to performance testing by the vendor. <br />\\n•  Generally, Pipelines tend to have a higher rate of failure at age two. <br />\\n•  The assumed maintenance date is after the second year, however ideally it should be around the end of first year.  <br />\",\"text_height\":250}",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
];